### ISSUE TITLE
Import NEP-2 into Wallet

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-mamba#68] opened 2021-03-15 18:17 UTC
The user must input the current password to decrypt the key and will be asked to add the wallet password. The key will be saved on the NEP-6 wallet using the wallet password (same password for all accounts)

[CreateAccount(name: str, passphrase : str)](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/wallet.go#L89-L100)
[NewAccountFromEncryptedKey(nep2: string, password: string)](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/account.go#L177-L187)

**Comment by meevee98** [comment] 2021-05-03 17:09
Duplicate of #60 and #63

**Closed by meevee98** 2021-05-03 17:09 UTC
